language: python
python:
  - 3.3
  - 2.7
before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -y tabix
install:
 - pip install coveralls
script:
 - python setup.py test
 - python -m coverage run --source=./clinicalfilter setup.py test
after_success:
 - coveralls
