language: python
python:
  - 2.7
  - 3.4
  - 3.6
before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -y tabix
 - pip install --upgrade pip setuptools wheel
 - pip install --only-binary=all pytabix pysam coveralls
script:
 - python setup.py test
 - python -m coverage run --source=./clinicalfilter setup.py test
after_success:
 - coveralls
